# AUTOGENERATED! DO NOT EDIT! File to edit: BearDetectorApp.ipynb.

# %% auto 0
__all__ = ['learn', 'categories', 'image', 'label', 'examples', 'intf', 'is_bear', 'classify_image']

# %% BearDetectorApp.ipynb 14
from fastai.vision.all import *

import gradio as gr

def is_bear(x): return x[0].isuppoer()

# %% BearDetectorApp.ipynb 16
learn = load_learner('./model.pkl')

# %% BearDetectorApp.ipynb 19
categories = learn.dls.vocab
def classify_image(img):
    pred, idx, probs = learn.predict(img)
    return dict(zip(categories, map(float, probs)))

# %% BearDetectorApp.ipynb 21
image = gr.Image(height=192,width=192)
label = gr.Label()
examples = ['./grizzly-1.jpg', './black-1.jpg', './teddy-1.jpg']

intf = gr.Interface(fn=classify_image, inputs=image, outputs=label, examples=examples)
intf.launch(inline=False)
