# AUTOGENERATED! DO NOT EDIT! File to edit: SealClassifierApp.ipynb.

# %% auto 0
__all__ = ['learn', 'categories', 'image', 'label', 'examples', 'intf', 'is_seal', 'classify_image']

# %% SealClassifierApp.ipynb 12
from fastai.vision.all import *

import gradio as gr

def is_seal(x): return x[0].isuppoer()

# %% SealClassifierApp.ipynb 14
learn = load_learner('./model.pkl')

# %% SealClassifierApp.ipynb 17
categories = learn.dls.vocab
def classify_image(img):
    pred, idx, probs = learn.predict(img)
    return dict(zip(categories, map(float, probs)))

# %% SealClassifierApp.ipynb 19
image = gr.Image(height=192,width=192)
label = gr.Label()
examples = ['./Odobenidae-1.jpg', './Phocidae-1.jpg', './Otariidae-1.jpg']

intf = gr.Interface(fn=classify_image, inputs=image, outputs=label, examples=examples)
intf.launch(inline=False)
